[2023-05-08T10:00:18.992+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T10:00:17.696488+00:00 [queued]>
[2023-05-08T10:00:19.000+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T10:00:17.696488+00:00 [queued]>
[2023-05-08T10:00:19.000+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-08T10:00:19.009+0000] {taskinstance.py:1350} INFO - Executing <Task(SparkSubmitOperator): spark_load_stock_data> on 2023-05-08 10:00:17.696488+00:00
[2023-05-08T10:00:19.013+0000] {standard_task_runner.py:57} INFO - Started process 416 to run task
[2023-05-08T10:00:19.016+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'upload_to_gcs', 'spark_load_stock_data', 'manual__2023-05-08T10:00:17.696488+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmp2utwtjjw']
[2023-05-08T10:00:19.016+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask spark_load_stock_data
[2023-05-08T10:00:19.056+0000] {task_command.py:410} INFO - Running <TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T10:00:17.696488+00:00 [running]> on host e1ef748a539e
[2023-05-08T10:00:19.124+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_gcs' AIRFLOW_CTX_TASK_ID='spark_load_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T10:00:17.696488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T10:00:17.696488+00:00'
[2023-05-08T10:00:19.133+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-05-08T10:00:19.133+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 391, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 335, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 247, in _mask_cmd
    ' '.join(connection_cmd),
TypeError: sequence item 9: expected str instance, int found
[2023-05-08T10:00:19.140+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_to_gcs, task_id=spark_load_stock_data, execution_date=20230508T100017, start_date=20230508T100018, end_date=20230508T100019
[2023-05-08T10:00:19.149+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task spark_load_stock_data (sequence item 9: expected str instance, int found; 416)
[2023-05-08T10:00:19.188+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T10:00:19.217+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
